server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${POSTGRESQL_URI:jdbc:postgresql://localhost:5432/socrates}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME:root}
    password: ${POSTGRESQL_PASSWORD:root}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
      auto-index-creation: true
      database: chatdb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Swagger springdoc-ui Configuration
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true              # 캐시 사용 여부
  api-docs:
    path: /api/analytics/api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8081/swagger-ui/index.html>
    path: /api/analytics/docs         # Swagger UI 접근 경로 => <http://localhost:8081/api/analytics/docs>
    tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    urls:
      - url: /api/analytics/api-docs/json
        name: Analytics API
