server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${POSTGRESQL_URI:jdbc:postgresql://localhost:5432/socrates}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME:root}
    password: ${POSTGRESQL_PASSWORD:root}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
      auto-index-creation: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true