spring:
  datasource:
    url: ${POSTGRESQL_URI:jdbc:postgresql://localhost:5432/socrates}
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
      auto-index-creation: true
      database: chatdb

  jpa:
    hibernate:
      ddl-auto: update