spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socrates
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update